name: cafemixes
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  share_plus: ^10.1.2
  flutter_email_sender: ^6.0.3
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.0.5

flutter:

  uses-material-design: true

  assets:
      - assets/icons/book.svg
      - assets/icons/cafe.svg
      - assets/icons/fav.svg
      - assets/icons/user.svg
      - assets/coffe.png
      - assets/cuestionario.json
flutter_native_splash:
  color: "#ffffff" # Color de fondo de la SplashScreen
  image: assets/coffe.png # Ruta a la imagen que quieres mostrar
  android: true
  ios: true
  web: false # Si estás desarrollando para la web, cámbialo a true
